import { type NextPage } from "next";
import Head from "next/head";
import List from "~/components/List";

export interface Name {
  firstName: string;
  lastName: string;
}

export interface Address {
  street: string;
  city: string;
}

const Home: NextPage = () => {
  const nameData: Name[] = [
    { firstName: "John", lastName: "Doe" },
    { firstName: "Jane", lastName: "Dawson" },
    { firstName: "Jack", lastName: "Bean" },
  ];

  const addressData: Address[] = [
    {
      street: "123 Main St",
      city: "Edmonton",
    },
    {
      street: "456 Main St",
      city: "Calgary",
    },
    {
      street: "789 Main St",
      city: "Toronto",
    },
  ];

  return (
    <>
      <Head>
        <title>Hello Sekai</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen flex-col items-center justify-center text-xl">
        <span>Hello World</span>
        <ul>
          {nameData.map((name) => (
            <List<Name>
              key={name.firstName}
              data={name}
              render={(name) => (
                <span>
                  {name.firstName} - {name.lastName}
                </span>
              )}
            />
          ))}
        </ul>
        <br />
        <ul>
          {addressData.map((address) => (
            <List<Address>
              key={address.city}
              data={address}
              render={(address) => (
                <span>
                  {address.city} - {address.street}
                </span>
              )}
            />
          ))}
        </ul>
      </div>
    </>
  );
};

export default Home;
