import { type NextPage } from "next";
import Head from "next/head";
import ListExample from "~/components/ListExample";
import { addressData } from "~/constants/data";

export interface Name {
  firstName: string;
  lastName: string;
}

const Home: NextPage = () => {
  const nameData: Name[] = [
    { firstName: "John", lastName: "Doe" },
    { firstName: "Jane", lastName: "Dawson" },
    { firstName: "Jack", lastName: "Bean" },
  ];

  return (
    <>
      <Head>
        <title>Hello Sekai</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen flex-col items-center justify-center text-xl">
        <span>Hello Sekai</span>
        <ul>
          {nameData.map((name) => (
            <ListExample data={name} key={name.firstName} />
          ))}
        </ul>
        -----------------------------------------------
        <ul>
          {addressData.map((address) => (
            <ListExample data={address} key={address.city} />
          ))}
        </ul>
        <br />
      </div>
    </>
  );
};

export default Home;
