import { type NextPage } from "next";
import Head from "next/head";

export interface Name {
  firstName: string;
  lastName: string;
}

const Home: NextPage = () => {
  const nameData: Name[] = [
    { firstName: "John", lastName: "Doe" },
    { firstName: "Jane", lastName: "Dawson" },
    { firstName: "Jack", lastName: "Bean" },
  ];

  return (
    <>
      <Head>
        <title>Hello Sekai</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen flex-col items-center justify-center text-xl">
        <span>Hello World</span>
        <ul>
          {nameData.map((name) => (
            <li className="list-disc" key={name.firstName}>
              <span>
                {name.firstName} - {name.lastName}
              </span>
            </li>
          ))}
        </ul>
        <br />
      </div>
    </>
  );
};

export default Home;
